// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm-gS6gT-5zCX-y4rC7CFciTL1rU9eOCw',
    appId: '1:298523946122:web:2512a86274b67a86b55173',
    messagingSenderId: '298523946122',
    projectId: 'pizzapp-9d345',
    authDomain: 'pizzapp-9d345.firebaseapp.com',
    databaseURL: 'https://pizzapp-9d345-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pizzapp-9d345.appspot.com',
    measurementId: 'G-MCQNG9BW7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVjgCaviSoUDV22fTbAs3y4RKh7umw7Sg',
    appId: '1:298523946122:android:77ea03e9b4cc7311b55173',
    messagingSenderId: '298523946122',
    projectId: 'pizzapp-9d345',
    databaseURL: 'https://pizzapp-9d345-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pizzapp-9d345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHAm0_YBCIv-YmFQ9F0B1JChMTcRuwHD8',
    appId: '1:298523946122:ios:16d04ec8dd129385b55173',
    messagingSenderId: '298523946122',
    projectId: 'pizzapp-9d345',
    databaseURL: 'https://pizzapp-9d345-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pizzapp-9d345.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHAm0_YBCIv-YmFQ9F0B1JChMTcRuwHD8',
    appId: '1:298523946122:ios:864b871e5783a690b55173',
    messagingSenderId: '298523946122',
    projectId: 'pizzapp-9d345',
    databaseURL: 'https://pizzapp-9d345-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pizzapp-9d345.appspot.com',
    iosBundleId: 'com.example.pizzaApp.RunnerTests',
  );
}
